= lab 15
Nadeŭka <nadevko@riseup.net>
v1.0, 2024-03-04

== Общее задание

Составить хеш-функцию в соответствии с заданным вариантом и проанализировать ее.
При необходимости доработать хеш-функцию. Используя полученную хеш-функцию
разработать на языке программирования C++ программу, которая должна выполнять
следующие функции:

. создавать хеш-таблицу;
. добавлять элементы в хеш-таблицу;
. просматривать хеш-таблицу;
. искать элементы в хеш-таблице;
. удалять элементы из хеш-таблицы.

== Описание хеш-функции

Хеш-функция основана на возведении суммы кодов символов ключа в квадрат и
извлечение из полученного квадрата нескольких средних цифр. При этом коды
символов умножаем на частное кода и произведения тройки на порядковый номер
символа в ключе (1ч6). Звучит убого, вот так выглядит формула суммы:

где - код символа с индексом "i";

Возведенная в квадрат сумма колеблется от 7997584 до 22781529, а это семизначное
или восьмизначное число. Для адресации сегментов хеш-таблицы необходимо
четырехзначное число, не превышающее 2000. Откинем у квадрата суммы 2 первых и
два последних разряда, так у нас получится трехзначное или четырехзначное число.
Для того, чтобы адрес не превысил максимально допустимый адрес 1999, будем брать
остаток от деления на 2000 до тех пор, пока он не попадет в нужный диапазон.

== Экспериментальный анализ хеш-функции

Экспериментальное исследование проводится следующим образом:

. формируются случайным образом ключи заданного формата в количестве,
  превышающем количество сегментов хеш-таблицы в 2...3 раза;
. для каждого сформированного ключа вычисляется хеш-функция, и подсчитывается,
  сколько раз вычислялся адрес того или иного сегмента хеш-таблицы.
